# Generated by Django 3.1.4 on 2021-03-03 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalserver',
            name='env',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cmdb.env', verbose_name='环境'),
        ),
        migrations.AddField(
            model_name='server',
            name='env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ra_server', to='cmdb.env', verbose_name='环境'),
        ),
    ]
