# Generated by Django 3.1.4 on 2021-01-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='service_port',
            field=models.IntegerField(default=0, verbose_name='服务端口'),
        ),
        migrations.AddField(
            model_name='app',
            name='zip_package_name',
            field=models.CharField(default='demo.zio', max_length=255, verbose_name='应用压缩包'),
        ),
        migrations.AddField(
            model_name='historicalapp',
            name='service_port',
            field=models.IntegerField(default=0, verbose_name='服务端口'),
        ),
        migrations.AddField(
            model_name='historicalapp',
            name='zip_package_name',
            field=models.CharField(default='demo.zio', max_length=255, verbose_name='应用压缩包'),
        ),
        migrations.AlterField(
            model_name='app',
            name='git_app_id',
            field=models.IntegerField(default=0, verbose_name='Git应用ID'),
        ),
        migrations.AlterField(
            model_name='historicalapp',
            name='git_app_id',
            field=models.IntegerField(default=0, verbose_name='Git应用ID'),
        ),
    ]
