# Generated by Django 3.1.4 on 2021-01-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20210116_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrelease',
            name='nginx_url',
        ),
        migrations.RemoveField(
            model_name='historicalrelease',
            name='salt_path',
        ),
        migrations.RemoveField(
            model_name='release',
            name='nginx_url',
        ),
        migrations.RemoveField(
            model_name='release',
            name='salt_path',
        ),
        migrations.AddField(
            model_name='historicalrelease',
            name='zip_package_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='压缩制品库路径'),
        ),
        migrations.AddField(
            model_name='release',
            name='zip_package_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='压缩制品库路径'),
        ),
    ]
