# Generated by Django 3.1.4 on 2021-03-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20210303_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreleasehistory',
            name='log_no',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='部署批次'),
        ),
        migrations.AddField(
            model_name='historicalserverhistory',
            name='log_no',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='部署批次'),
        ),
        migrations.AddField(
            model_name='releasehistory',
            name='log_no',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='部署批次'),
        ),
        migrations.AddField(
            model_name='serverhistory',
            name='log_no',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='部署批次'),
        ),
    ]
