# Generated by Django 3.1.4 on 2021-01-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20210103_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrelease',
            name='nginx_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='制品库路径'),
        ),
        migrations.AlterField(
            model_name='historicalrelease',
            name='salt_path',
            field=models.CharField(max_length=255, verbose_name='执行脚本路径'),
        ),
        migrations.AlterField(
            model_name='release',
            name='nginx_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='制品库路径'),
        ),
        migrations.AlterField(
            model_name='release',
            name='salt_path',
            field=models.CharField(max_length=255, verbose_name='执行脚本路径'),
        ),
    ]
