# Generated by Django 3.1.4 on 2021-01-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20210116_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrelease',
            name='deploy_script_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='部署脚本路径'),
        ),
        migrations.AddField(
            model_name='release',
            name='deploy_script_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='部署脚本路径'),
        ),
    ]
