# Generated by Django 3.1.4 on 2021-03-06 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20210306_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='op_log_no',
            new_name='op_no',
        ),
        migrations.RenameField(
            model_name='historicalapp',
            old_name='op_log_no',
            new_name='op_no',
        ),
    ]
